"""Generate docs/api/parity-matrix.md from the canonical operation
catalog — the doc is a build artifact, not a hand-maintained list.

    python tools/parity_matrix.py            # regenerate
    python tools/parity_matrix.py --check    # fail if stale (CI)
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

OUT = os.path.join(os.path.dirname(__file__), '..', 'docs', 'api',
                   'parity-matrix.md')

_HEADER = """<!-- GENERATED by tools/parity_matrix.py — do not edit by hand.
     Source of truth: engine/domain/operations.py -->

# Operation parity matrix

`vnc-remote` (CLI), `/api/v1` (REST) and the admin SPA expose the same
capabilities because all three invoke the same Engine use cases. This
table is generated from the canonical catalog — a capability that
exists in one transport but not another shows up here as a gap (or a
deliberate `cli-only`/`api-only` cell).

| Operation | Riesgo | CLI | API | UI | Permiso | Step-up | Ejecución | Audit | Reversible |
|---|---|---|---|---|---|---|---|---|---|
"""


def render() -> str:
    from vnc_remote_secure.engine.domain.operations import parity_matrix
    lines = [_HEADER]
    for r in parity_matrix():
        step_up = r['step_up']
        lines.append(
            f"| `{r['operation']}` | {r['risk']} "
            f"| {('`' + r['cli'] + '`') if r['cli'] != '-' else '—'} "
            f"| {('`' + r['api'] + '`') if r['api'] != '-' else '—'} "
            f"| {'sí' if r['ui'] else '—'} "
            f"| `{r['perm'] or 'public'}` | {step_up} "
            f"| {r['execution']} | `{r['audit']}` | {r['reversible']} |")
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    body = render()
    if '--check' in sys.argv:
        current = open(OUT, encoding='utf-8').read() if os.path.isfile(OUT) else ''
        if current != body:
            print('parity-matrix.md is stale — run tools/parity_matrix.py')
            return 1
        print('parity-matrix.md up to date')
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(body)
    print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
